Repository spotify-api/spotify-api.js, pull requests merged in 2022-07, with the labels that each got.

#149 Fix several playlist create / edit API by using request body
  src/managers/Playlist.ts
Labels: enhancement

#160 Fix README typo in code for Rate Limit
  README.md
Labels: documentation

#158 Fix spelling in reorderItems for uris parameter
  src/managers/Playlist.ts
Labels: bugfix
